export const ENTITIES_REQUEST = 'ENTITIES_REQUEST';
export const ENTITIES_SUCCESS = 'ENTITIES_SUCCESS';
export const ENTITIES_FAILURE = 'ENTITIES_FAILURE';

export const INIT_TODOS = "INIT_TODOS";
export const HANDLE_ADDING_MODE = "HANDLE_ADDING_MODE";
export const DELETED_TODO = "DELETED_TODO";

export const EDIT_TODO_TITLE = "EDIT_TODO_TITLE";
export const CANCEL_EDIT_TODO_TITLE = "CANCEL_EDIT_TODO_TITLE";
export const DONE_EDIT_TODO_TITLE = "DONE_EDIT_TODO_TITLE";

export const RESCHEDULE_TODO = "RESCHEDULE_TODO";
export const DONE_RESCHEDULE_TODO = "DONE_RESCHEDULE_TODO";