export const ENTITIES_REQUEST = 'ENTITIES_REQUEST';
export const ENTITIES_SUCCESS = 'ENTITIES_SUCCESS';
export const ENTITIES_FAILURE = 'ENTITIES_FAILURE';

export const INIT_TODOS = "INIT_TODOS";
export const HANDLE_ADDING_MODE = "HANDLE_ADDING_MODE";